"""File-based intent test cases for OVOS skills.

Lets skill authors describe expected intent routing as plain-text files
under ``test/end2end/cases/<lang>/`` — adding a phrase, intent, or whole
new language is a pure text edit; no Python required.

Layout
------

::

    test/end2end/cases/
        <lang>/
            <IntentName>.intent.test     # one utterance per line, expected
                                         # to match <IntentName>
            no_match.test                # utterances expected to match
                                         # NO intent of this skill

``#`` comments and blank lines are ignored.

Usage (one call, in a test module owned by the skill)
-----------------------------------------------------

::

    # test/end2end/test_intents.py
    from pathlib import Path
    from ovoscope.intent_cases import register_intent_case_tests

    register_intent_case_tests(
        globals(),
        skill_id="ovos-skill-personal.openvoiceos",
        handlers={
            "WhoAreYou.intent": "PersonalSkill.handle_who_are_you_intent",
            "WhatAreYou.intent": "PersonalSkill.handle_what_are_you_intent",
            # ...
        },
        cases_dir=Path(__file__).parent / "cases",
    )

The call creates four ``unittest.TestCase`` classes in the caller's
module — one per pipeline family (Padatious, Padacioso, Model2Vec) plus
one for the full default OVOS stack — each containing one ``test_*``
method per (lang, utterance) pair. A test passes if any tier of its
pipeline family routes the utterance to the expected intent, which
matches realistic production cascade behaviour.

Override the generated set with ``pipelines={"name": [stage, ...]}`` if
you only want a subset, or to test against custom pipeline stages.
"""
from __future__ import annotations

import dataclasses
import time
from copy import deepcopy
from pathlib import Path
from typing import Dict, Iterable, Iterator, List, Optional, Union
from unittest import TestCase

from ovos_bus_client.message import Message
from ovos_bus_client.session import Session
from ovos_utils.log import LOG

# Imports from the top-level package — guarded to avoid a circular import at
# module load. The runtime calls happen well after package init.
from ovoscope import (DEFAULT_TEST_PIPELINE, End2EndTest, M2V_PIPELINE,
                      PADACIOSO_PIPELINE, PADATIOUS_PIPELINE, get_minicroft)

__all__ = [
    "IntentCase",
    "load_intent_cases",
    "assert_intent_case",
    "register_intent_case_tests",
    "DEFAULT_IGNORE_MESSAGES",
    "DEFAULT_PIPELINE_FAMILIES",
]

DEFAULT_IGNORE_MESSAGES: List[str] = [
    "speak",
    "mycroft.audio.play_sound",
    "ovos.common_play.stop.response",
]

# Named pipeline families generated by default.
DEFAULT_PIPELINE_FAMILIES: Dict[str, List[str]] = {
    "Padatious": PADATIOUS_PIPELINE,
    "Padacioso": PADACIOSO_PIPELINE,
    "M2V": M2V_PIPELINE,
    "DefaultPipeline": DEFAULT_TEST_PIPELINE,
}


@dataclasses.dataclass(frozen=True)
class IntentCase:
    """A single expectation: ``utterance`` in ``lang`` should match ``intent``.

    ``intent`` is ``None`` to assert no intent of the skill under test
    fires (the utterance falls through to ``complete_intent_failure``).
    """
    lang: str
    utterance: str
    intent: Optional[str]
    source: Path


# ---------------------------------------------------------------------------
# Case-file discovery
# ---------------------------------------------------------------------------
def _read_lines(path: Path) -> List[str]:
    out: List[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line and not line.startswith("#"):
            out.append(line)
    return out


def load_intent_cases(cases_dir: Union[str, Path],
                      known_intents: Optional[Iterable[str]] = None
                      ) -> List[IntentCase]:
    """Discover every ``IntentCase`` under ``cases_dir``.

    Args:
        cases_dir: directory containing ``<lang>/<Intent>.intent.test`` and
            optionally ``<lang>/no_match.test`` files.
        known_intents: if given, every ``<Intent>.intent`` filename found
            is validated against this set — a typo will raise
            ``AssertionError`` instead of silently being skipped.

    Returns:
        List of cases in stable (lang, file, line) order.
    """
    base = Path(cases_dir)
    if not base.is_dir():
        return []
    known = set(known_intents) if known_intents is not None else None
    cases: List[IntentCase] = []
    for lang_dir in sorted(base.iterdir()):
        if not lang_dir.is_dir() or lang_dir.name.startswith("_"):
            continue
        lang = lang_dir.name
        for case_file in sorted(lang_dir.glob("*.test")):
            if case_file.name == "no_match.test":
                expected: Optional[str] = None
            elif case_file.stem.endswith(".intent"):
                expected = case_file.stem  # "<IntentName>.intent"
                if known is not None and expected not in known:
                    raise AssertionError(
                        f"{case_file} targets unknown intent "
                        f"{expected!r}; expected one of {sorted(known)}")
            else:
                continue
            for utt in _read_lines(case_file):
                cases.append(IntentCase(lang=lang, utterance=utt,
                                        intent=expected, source=case_file))
    return cases


# ---------------------------------------------------------------------------
# Single-case assertion
# ---------------------------------------------------------------------------
def assert_intent_case(minicroft, skill_id: str, handlers: Dict[str, str],
                       case: IntentCase, pipeline: List[str],
                       *,
                       ignore_messages: Optional[List[str]] = None,
                       timeout: float = 30) -> None:
    """Fire ``case.utterance`` through ``pipeline`` and assert routing.

    Asserts that an ``IntentCase`` with ``intent=None`` falls through to
    ``complete_intent_failure``; otherwise asserts the expected intent
    and handler-lifecycle messages fire in order.

    Args:
        minicroft: a running ``MiniCroft`` instance with ``skill_id`` loaded.
        skill_id: the full skill id under test (e.g. ``"my-skill.author"``).
        handlers: ``{intent_name: handler_method_name}`` for the skill.
        case: the case to run.
        pipeline: list of pipeline stage ids to populate
            ``session.pipeline`` with.
        ignore_messages: extra non-deterministic / noisy message types to
            filter out of the comparison.
        timeout: per-case execution timeout, in seconds.
    """
    ignored = list(ignore_messages or DEFAULT_IGNORE_MESSAGES)

    session = Session(f"intent-case-{case.lang}-{case.utterance[:24]}")
    session.lang = case.lang
    session.pipeline = list(pipeline)

    source = Message(
        "recognizer_loop:utterance",
        {"utterances": [case.utterance], "lang": case.lang},
        {"session": session.serialize()},
    )

    if case.intent is None:
        final_session = deepcopy(session)
        expected_messages = [
            source,
            Message("complete_intent_failure",
                    {"utterances": [case.utterance], "lang": case.lang}, {}),
            Message("ovos.utterance.handled", {}, {}),
        ]
        test = End2EndTest(
            minicroft=minicroft,
            skill_ids=[skill_id],
            eof_msgs=["ovos.utterance.handled"],
            flip_points=["recognizer_loop:utterance"],
            ignore_messages=ignored,
            source_message=source,
            final_session=final_session,
            expected_messages=expected_messages,
            test_msg_data=False,
            test_msg_context=False,
        )
    else:
        if case.intent not in handlers:
            raise AssertionError(
                f"No handler mapping for intent {case.intent!r} "
                f"(case from {case.source}). Add it to ``handlers``.")
        handler = handlers[case.intent]
        final_session = deepcopy(session)
        final_session.active_skills = [(skill_id, 0.0)]
        expected_messages = [
            source,
            Message(f"{skill_id}.activate", {}, {"skill_id": skill_id}),
            Message(f"{skill_id}:{case.intent}",
                    {"utterance": case.utterance, "lang": case.lang},
                    {"skill_id": skill_id}),
            Message("mycroft.skill.handler.start",
                    {"name": handler}, {"skill_id": skill_id}),
            Message("mycroft.skill.handler.complete",
                    {"name": handler}, {"skill_id": skill_id}),
            Message("ovos.utterance.handled", {}, {"skill_id": skill_id}),
        ]
        test = End2EndTest(
            minicroft=minicroft,
            skill_ids=[skill_id],
            eof_msgs=["ovos.utterance.handled"],
            flip_points=["recognizer_loop:utterance"],
            ignore_messages=ignored,
            source_message=source,
            final_session=final_session,
            activation_points=[f"{skill_id}:{case.intent}"],
            expected_messages=expected_messages,
        )
    test.execute(timeout=timeout)


# ---------------------------------------------------------------------------
# Shared minicroft helper
# ---------------------------------------------------------------------------
_SHARED_MINICROFT_KEY = "_ovoscope_shared_minicroft"


def _shared_minicroft(skill_id: str, langs: List[str], m2v_warmup: float):
    """Lazily create one MiniCroft and warm m2v's label index.

    Caches the instance on a process-global so every generated class
    shares the same boot.
    """
    cache = globals().setdefault(_SHARED_MINICROFT_KEY, {})
    key = (skill_id, tuple(langs))
    if key not in cache:
        LOG.set_level("CRITICAL")
        secondary = [l for l in langs if l != "en-US"]
        mc = get_minicroft([skill_id], secondary_langs=secondary or None)
        # m2v consumes ``padatious:register_intent`` to (re)build its label
        # index; ``mycroft.ready`` triggers ``handle_sync_intents``. Without
        # this nudge the first m2v call logs "No model classes match
        # registered intents" and falls through.
        mc.bus.emit(Message("mycroft.ready", {}, {}))
        if m2v_warmup > 0:
            time.sleep(m2v_warmup)
        cache[key] = mc
    return cache[key]


# ---------------------------------------------------------------------------
# Test-class generator
# ---------------------------------------------------------------------------
def _slug(s: str) -> str:
    out = []
    for ch in s:
        if ch.isalnum():
            out.append(ch)
        elif ch in " -_/":
            out.append("_")
    return "".join(out).strip("_") or "x"


def _build_test_class(name: str, pipeline: List[str], cases: List[IntentCase],
                      skill_id: str, handlers: Dict[str, str],
                      langs: List[str],
                      ignore_messages: Optional[List[str]],
                      timeout: float,
                      m2v_warmup: float,
                      doc: str) -> type:
    def _make(case: IntentCase):
        def _test(self):
            mc = _shared_minicroft(skill_id, langs, m2v_warmup)
            assert_intent_case(mc, skill_id, handlers, case, pipeline,
                               ignore_messages=ignore_messages,
                               timeout=timeout)
        label = case.intent.split(".")[0] if case.intent else "no_match"
        _test.__doc__ = (f"[{case.lang}] {case.utterance!r} -> "
                         f"{case.intent if case.intent else 'no match'}  ({name})")
        # Attach metadata for the pytest accuracy/coverage reporter.
        _test._intent_case = case  # type: ignore[attr-defined]
        _test._intent_case_pipeline = name  # type: ignore[attr-defined]
        _test._intent_case_skill_id = skill_id  # type: ignore[attr-defined]
        return _test, label

    body: Dict[str, object] = {"__doc__": doc}
    for case in cases:
        method, label = _make(case)
        slug = _slug(case.utterance)
        attr = f"test_{case.lang.replace('-', '_')}__{label}__{slug}"
        # avoid clobbers if two utterances slug-collide
        base = attr
        n = 2
        while attr in body:
            attr = f"{base}_{n}"
            n += 1
        body[attr] = method
    return type(name, (TestCase,), body)


def register_intent_case_tests(
        target_globals: dict,
        *,
        skill_id: str,
        handlers: Dict[str, str],
        cases_dir: Union[str, Path],
        pipelines: Optional[Dict[str, List[str]]] = None,
        ignore_messages: Optional[List[str]] = None,
        timeout: float = 30,
        m2v_warmup: float = 10.0,
        ) -> Dict[str, type]:
    """Create per-pipeline ``TestCase`` classes in ``target_globals``.

    Args:
        target_globals: pass ``globals()`` from the caller test module —
            generated classes are inserted here so pytest collects them.
        skill_id: full skill plugin id (e.g. ``"my-skill.author"``).
        handlers: mapping ``{"<IntentName>.intent": "<HandlerMethodName>"}``
            covering every intent referenced by case files.
        cases_dir: directory containing ``<lang>/<Intent>.intent.test`` and
            optional ``<lang>/no_match.test`` files.
        pipelines: ``{class_suffix: pipeline_stage_list}`` to override the
            default per-family classes. Each entry becomes a
            ``Test<class_suffix>`` class. Defaults to one class per family
            in :data:`DEFAULT_PIPELINE_FAMILIES`.
        ignore_messages: extra message types to filter out of comparison.
        timeout: per-case execution timeout, in seconds.
        m2v_warmup: seconds to sleep after booting the MiniCroft so the
            m2v pipeline finishes syncing its label index. Set to 0 if
            you're not running m2v cases.

    Returns:
        ``{class_name: class_object}`` for every class created.
    """
    cases = load_intent_cases(cases_dir, known_intents=handlers.keys())
    if not cases:
        # Empty cases dir: skip silently so a freshly-copied template
        # doesn't fail collection before any .test files are added.
        return {}

    langs = sorted({c.lang for c in cases})
    families = pipelines if pipelines is not None else DEFAULT_PIPELINE_FAMILIES

    created: Dict[str, type] = {}
    for suffix, pipeline in families.items():
        cls_name = f"Test{suffix}"
        doc = (f"ovoscope intent-case tests for {skill_id} on pipeline "
               f"{pipeline!r}.")
        cls = _build_test_class(cls_name, pipeline, cases, skill_id, handlers,
                                langs, ignore_messages, timeout, m2v_warmup,
                                doc)
        target_globals[cls_name] = cls
        created[cls_name] = cls
    return created
