name: Run Tests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovoscope/version.py'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'docs/**'
  push:
    branches:
      - dev
    paths-ignore:
      - 'ovoscope/version.py'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  unit_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    secrets: inherit
    with:
      python_version: "3.14"
      install_extras: "-e .[pydantic]"
      test_path: "test/unittests/"
      coverage_source: "ovoscope"
